# ArchBuilder.AI Prometheus Configuration
# Monitoring and metrics collection

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'archbuilder'
    replica: 'prometheus-1'

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s
    metrics_path: /metrics

  # ArchBuilder Cloud Server
  - job_name: 'archbuilder-cloud-server'
    static_configs:
      - targets: ['cloud-server:8000']
    scrape_interval: 10s
    metrics_path: /metrics
    scrape_timeout: 5s
    honor_labels: true

  # PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s
    metrics_path: /metrics

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
    metrics_path: /metrics

  # Nginx
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    scrape_interval: 30s
    metrics_path: /nginx_status

  # Node Exporter (if available)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # cAdvisor (if available)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s

  # RAGFlow Service
  - job_name: 'ragflow'
    static_configs:
      - targets: ['ragflow:8000']
    scrape_interval: 30s
    metrics_path: /metrics
    scrape_timeout: 10s

# Storage configuration
storage:
  tsdb:
    retention.time: 30d
    retention.size: 10GB
    wal-compression: true

# Remote write configuration (optional)
# remote_write:
#   - url: "https://prometheus-remote-write-endpoint/api/v1/write"
#     basic_auth:
#       username: "username"
#       password: "password"

# Recording rules
recording_rules:
  - name: "archbuilder.rules"
    rules:
      - record: "archbuilder:request_rate"
        expr: "rate(http_requests_total[5m])"
      
      - record: "archbuilder:error_rate"
        expr: "rate(http_requests_total{status=~'5..'}[5m])"
      
      - record: "archbuilder:response_time_p95"
        expr: "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m]))"
